# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
baseurl: "/me" # the subpath of your site, e.g. /blog
# url: "https://127.0.0.1" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://yambottle.github.io" # the base hostname & protocol for your site, e.g. http://example.com
host: 127.0.0.1
port: 4010
name: Drew Yang
email: drew.yang.dev@gmail.com
phone: 214-727-9608
location: Houston, TX
linkedin: https://www.linkedin.com/in/drewyang/
github: https://yambottle.github.io/me/

# Build settings
encoding: "utf-8"
# To work with ~/_layout/compress.html
#
# compress_html:
#   clippings: []
#   comments: []
#   endings: []
#   ignore:
#     envs: []
#   blanklines: false
#   profile: false
#   startings: []

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
  - example/
  - Makefile
  - .gitignore
  - README.md